use template for build and test matrix jobs

diff --git a/.github/workflows/build_robotframework_aio.yml b/.github/workflows/build_robotframework_aio.yml
--- a/.github/workflows/build_robotframework_aio.yml
+++ b/.github/workflows/build_robotframework_aio.yml
@@ -73,9 +73,9 @@ jobs:
       matrix:
         include:
           - type: robotframework-develop_6.1
-            REPO_CONFIG: "${{ github.workspace }}/config/repositories/repositories.conf"
+            REPO_CONFIG: "./config/repositories/repositories.conf"
           - type: unchanged-robotframework
-            REPO_CONFIG: "${{ github.workspace }}/config/repositories/repositories_no_robotframework.conf"
+            REPO_CONFIG: "./config/repositories/repositories_no_robotframework.conf"
     name: Build Linux packages
     runs-on: ubuntu-latest
     needs: [ tag-repos , trigger-aio ]
@@ -156,60 +156,23 @@ jobs:
           name: RobotFrameworkAIO_Reference-${{ matrix.type }}
           path: ${{ runner.workspace }}/robotframework-documentation/RobotFrameworkAIO/RobotFrameworkAIO_Reference.pdf
 
-  build-windows:
+  build-test-windows:
     strategy:
       matrix:
         include:
-          - type: robotframework-develop_6.1
-            REPO_CONFIG: "${{ github.workspace }}/config/repositories/repositories.conf"
-          - type: unchanged-robotframework
-            REPO_CONFIG: "${{ github.workspace }}/config/repositories/repositories_no_robotframework.conf"
-    name: Build Windows packages
-    runs-on: windows-latest
+          - build-type: robotframework-develop_6.1
+            repo-config: "./config/repositories/repositories.conf"
+          - build-type: unchanged-robotframework
+            repo-config: "./config/repositories/repositories_no_robotframework.conf"
     needs: [ tag-repos , trigger-aio ]
     if: ${{ ! failure() && ! cancelled() }}
-
-    steps:
-      - name: Support long path in git
-        run: git config --system core.longpaths true
-
-      - name: Checkout source
-        uses: actions/checkout@v3
-
-      - name: Install dependencies and set environment variables
-        shell: bash
-        run: |
-          . ./requirements_windows.sh
-          echo "GENDOC_LATEXPATH=$GENDOC_LATEXPATH" >> $GITHUB_ENV
-          echo "AIO_VERSION_DATE=$(date +%m.%Y)" >> $GITHUB_ENV
-          echo "AIO_VERSION=${TAG_NAME#[rd]e[vl]/aio/}" >> $GITHUB_ENV
-          echo "BUNDLE_VERSION_DATE=--bundle_version_date \"$(date +%m.%Y)\"" >> $GITHUB_ENV
-          echo "BUNDLE_VERSION=--bundle_version \"${TAG_NAME#[rd]e[vl]/aio/}\"" >> $GITHUB_ENV
-          echo "REPOSITORY=${{needs.trigger-aio.outputs.repository}}" >> $GITHUB_ENV
-          echo "PULL_REQUEST_BRANCH=${{needs.trigger-aio.outputs.branch}}" >> $GITHUB_ENV
-
-          # Update placeholders install-github-copilot-exts.sh script
-          sed -i "s|\$PLACEHOLDER_REF_URL|${GITHUB_COPILOT_REF_URL}|g" ./install/install-github-copilot-exts.sh
-
-      - name: Clone repositories
-        shell: bash
-        run: |
-          chmod +x ./cloneall
-          ./cloneall --config-file='${{ matrix.REPO_CONFIG }}'
-
-      - name: Install
-        shell: bash
-        run: ./install/install.sh
-
-      - name: Build
-        shell: bash
-        run: ./build --config-file='${{ matrix.REPO_CONFIG }}'
-
-      - name: Upload built package
-        uses: actions/upload-artifact@v3
-        with:
-          name: windows-package-${{ matrix.type }}
-          path: Output/
+    uses: ./.github/workflows/build_and_test_template.yml
+    secrets: inherit
+    with:
+      build-type: ${{ matrix.build-type }}
+      repo-config: ${{ matrix.repo-config }}
+      triggered-repo: ${{ needs.trigger-aio.outputs.repository }}
+      triggered-branch: ${{ needs.trigger-aio.outputs.branch }}
 
   # build-linux-unchanged-robotframework:
   #   name: Build Linux package with latest release of robotframework core
@@ -308,90 +271,90 @@ jobs:
   #         name: windows-unchanged-robotframework-package
   #         path: Output/
 
-  install-test-windows:
-    name: Test Windows package
-    runs-on: windows-latest
-    needs: [ build-windows  , trigger-aio ]
-    if: ${{ ! failure() && ! cancelled() }}
-    env:
-      RobotPythonPath: "C:/Program Files/RobotFramework/python39"
-      RobotTutorialPath: "C:/RobotTest/tutorial"
-      RobotPythonSitePackagesPath: "C:/Program Files/RobotFramework/python39/Lib/site-packages"
-      GENDOC_PLANTUML_PATH: "C:/Program Files/RobotFramework/robotvscode/data/extensions/jebbs.plantuml-2.17.5"
+  # install-test-windows:
+  #   name: Test Windows package
+  #   runs-on: windows-latest
+  #   needs: [ build-windows  , trigger-aio ]
+  #   if: ${{ ! failure() && ! cancelled() }}
+  #   env:
+  #     RobotPythonPath: "C:/Program Files/RobotFramework/python39"
+  #     RobotTutorialPath: "C:/RobotTest/tutorial"
+  #     RobotPythonSitePackagesPath: "C:/Program Files/RobotFramework/python39/Lib/site-packages"
+  #     GENDOC_PLANTUML_PATH: "C:/Program Files/RobotFramework/robotvscode/data/extensions/jebbs.plantuml-2.17.5"
 
-    steps:
-    - name: Support long path in git
-      run: git config --system core.longpaths true
+  #   steps:
+  #   - name: Support long path in git
+  #     run: git config --system core.longpaths true
 
-    - name: Checkout source
-      uses: actions/checkout@v3
+  #   - name: Checkout source
+  #     uses: actions/checkout@v3
 
-    - name: Clone repositories
-      shell: bash
-      run: |
-        export REPOSITORY="${{needs.trigger-aio.outputs.repository}}"
-        export PULL_REQUEST_BRANCH="${{needs.trigger-aio.outputs.branch}}"
-        chmod +x ./cloneall
-        ./cloneall
+  #   - name: Clone repositories
+  #     shell: bash
+  #     run: |
+  #       export REPOSITORY="${{needs.trigger-aio.outputs.repository}}"
+  #       export PULL_REQUEST_BRANCH="${{needs.trigger-aio.outputs.branch}}"
+  #       chmod +x ./cloneall
+  #       ./cloneall
 
-    - name: Download Windows installer package
-      uses: actions/download-artifact@v3
-      with:
-        name: windows-package
+  #   - name: Download Windows installer package
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: windows-package
 
-    - name: Install RobotFramework AIO on Windows
-      shell: cmd
-      run: ./scripts/install-windows.bat
+  #   - name: Install RobotFramework AIO on Windows
+  #     shell: cmd
+  #     run: ./scripts/install-windows.bat
 
-    - name: Run tests on Windows
-      shell: bash
-      run: |
-        "$RobotPythonPath/python" test/aio-test-trigger/aio-test-trigger.py 2>&1 | tee console_log.txt
-        # Get system error code from python program
-        exit_code=${PIPESTATUS[0]}
-        if [ $exit_code -ne 0 ]; then
-            exit 1
-        fi
+  #   - name: Run tests on Windows
+  #     shell: bash
+  #     run: |
+  #       "$RobotPythonPath/python" test/aio-test-trigger/aio-test-trigger.py 2>&1 | tee console_log.txt
+  #       # Get system error code from python program
+  #       exit_code=${PIPESTATUS[0]}
+  #       if [ $exit_code -ne 0 ]; then
+  #           exit 1
+  #       fi
 
-    - name: Run tests coverage on Windows
-      shell: bash
-      run: |
-        "$RobotPythonPath/python" test/aio-test-trigger/aio-test-coverage.py 2>&1 | tee console_log.txt
-        # Get system error code from python program
-        exit_code=${PIPESTATUS[0]}
+  #   - name: Run tests coverage on Windows
+  #     shell: bash
+  #     run: |
+  #       "$RobotPythonPath/python" test/aio-test-trigger/aio-test-coverage.py 2>&1 | tee console_log.txt
+  #       # Get system error code from python program
+  #       exit_code=${PIPESTATUS[0]}
 
-    - name: Generate release info
-      shell: cmd
-      run: |
-        "%RobotPythonPath%\python" .\tools\release_info\release_info.py --configfile ".\release_info_config_OSS.json"
-        move .\tools\release_info\release_info_RobotFramework_AIO_*.html ..\
-        move .\tools\release_info\release_changelog.html ..\
+  #   - name: Generate release info
+  #     shell: cmd
+  #     run: |
+  #       "%RobotPythonPath%\python" .\tools\release_info\release_info.py --configfile ".\release_info_config_OSS.json"
+  #       move .\tools\release_info\release_info_RobotFramework_AIO_*.html ..\
+  #       move .\tools\release_info\release_changelog.html ..\
     
-    - name: Generate tutorial doc
-      shell: cmd
-      run: |
-        "%RobotPythonPath%\python" ..\robotframework-tutorial\__setup\gen_doc_tutorial.py
+  #   - name: Generate tutorial doc
+  #     shell: cmd
+  #     run: |
+  #       "%RobotPythonPath%\python" ..\robotframework-tutorial\__setup\gen_doc_tutorial.py
          
-    - name: Upload test result as artifact
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
-        name: windows-aiotestlogfiles
-        # long path issue on Windows when upload artifact 
-        # https://github.com/actions/upload-artifact/issues/240
-        path: |
-          ${{ runner.workspace }}/[Rr]obotframework*/**/*/aiotestlogfiles/*
-          ${{ runner.workspace }}/[Pp]ython*/**/*/aiotestlogfiles/*
-          ${{ runner.workspace }}/[Rr]obotframework*/**/*/testlogfiles/*
-          ${{ runner.workspace }}/[Pp]ython*/**/*/testlogfiles/*
-          ${{ runner.workspace }}/Robotframework_AIO/console_log.txt
-          ${{ runner.workspace }}/[Rr]obotframework*/**/*/*/coverage_report/*
-          ${{ runner.workspace }}/[Pp]ython*/**/*/*/coverage_report/*
-          ${{ runner.workspace }}/[Rr]obotframework*/**/*/*/coverage_report/*
-          ${{ runner.workspace }}/[Pp]ython*/**/*/*/coverage_report/*
-          ${{ runner.workspace }}/release_info_RobotFramework_AIO_*.html
-          ${{ runner.workspace }}/release_changelog.html
-          ${{ runner.workspace }}/Robotframework_AIO/install-windows.log
+  #   - name: Upload test result as artifact
+  #     if: success() || failure()
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: windows-aiotestlogfiles
+  #       # long path issue on Windows when upload artifact 
+  #       # https://github.com/actions/upload-artifact/issues/240
+  #       path: |
+  #         ${{ runner.workspace }}/[Rr]obotframework*/**/*/aiotestlogfiles/*
+  #         ${{ runner.workspace }}/[Pp]ython*/**/*/aiotestlogfiles/*
+  #         ${{ runner.workspace }}/[Rr]obotframework*/**/*/testlogfiles/*
+  #         ${{ runner.workspace }}/[Pp]ython*/**/*/testlogfiles/*
+  #         ${{ runner.workspace }}/Robotframework_AIO/console_log.txt
+  #         ${{ runner.workspace }}/[Rr]obotframework*/**/*/*/coverage_report/*
+  #         ${{ runner.workspace }}/[Pp]ython*/**/*/*/coverage_report/*
+  #         ${{ runner.workspace }}/[Rr]obotframework*/**/*/*/coverage_report/*
+  #         ${{ runner.workspace }}/[Pp]ython*/**/*/*/coverage_report/*
+  #         ${{ runner.workspace }}/release_info_RobotFramework_AIO_*.html
+  #         ${{ runner.workspace }}/release_changelog.html
+  #         ${{ runner.workspace }}/Robotframework_AIO/install-windows.log
 
   install-test-linux:
     name: Test Linux package
@@ -465,7 +428,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    needs: [install-test-windows, install-test-linux]
+    needs: [build-test-windows, install-test-linux]
     if: ${{ ! failure() && ! cancelled() && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/rel/aio/') }}
 
     steps:
@@ -490,7 +453,7 @@ jobs:
   tag-to-publish-packges-to-pypi:
     name: Tag Python packages to trigger workflow for publishing to PyPI
     runs-on: ubuntu-latest
-    needs: [install-test-windows, install-test-linux]
+    needs: [build-test-windows, install-test-linux]
     if: ${{ ! failure() && ! cancelled() && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/rel/aio/') }}
 
     steps:
@@ -508,7 +471,7 @@ jobs:
   update-version-aio:
     name: Update version AIO
     runs-on: ubuntu-latest
-    needs: [install-test-windows, install-test-linux]
+    needs: [build-test-windows, install-test-linux]
     if: ${{ ! failure() && ! cancelled() && github.ref_type == 'tag' }}
 
     steps:
